
services:
  lab-01:
    build: .
    container_name: lab-01
    hostname: lab-01
    ports:
      - "2222:22"  # SSH port mapping
    environment:
      - ROOT_PASSWORD=labroot123
      - USER=labuser
      - USER_PASSWORD=labpass123
      - SUDO=true
    volumes:
      - lab-01-home:/home  # Persistent user home directories
      - lab-01-services:/etc/systemd/system  # Persistent systemd services
    networks:
      - lab-network
    restart: unless-stopped

  lab-02:
    build: .
    container_name: lab-02
    hostname: lab-02
    ports:
      - "2223:22"  # Different SSH port
    environment:
      - ROOT_PASSWORD=labroot123
      - USER=labuser
      - USER_PASSWORD=labpass123
      - SUDO=true
    volumes:
      - lab-02-home:/home
      - lab-02-services:/etc/systemd/system  # Persistent systemd services
    networks:
      - lab-network
    restart: unless-stopped

volumes:
  lab-01-home:
    name: lab-01-home
  lab-02-home:
    name: lab-02-home
  lab-01-services:
    name: lab-01-services
  lab-02-services:
    name: lab-02-services

networks:
  lab-network:
    name: lab-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16