name: Main CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  actions: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.21', '1.22']
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}

    - name: Download dependencies
      run: make deps

    - name: Run tests
      run: make test

    - name: Test build
      run: make build

    - name: Test cross-platform builds
      run: |
        cd app
        # Test building for all platforms
        GOOS=linux GOARCH=amd64 go build -o ../lab-linux-amd64 .
        GOOS=linux GOARCH=arm64 go build -o ../lab-linux-arm64 .
        GOOS=darwin GOARCH=amd64 go build -o ../lab-darwin-amd64 .
        GOOS=darwin GOARCH=arm64 go build -o ../lab-darwin-arm64 .

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Download dependencies
      run: make deps

    - name: Run go fmt
      run: |
        cd app
        if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then
          echo "Go code is not formatted:"
          gofmt -s -l .
          exit 1
        fi

    - name: Run go vet
      run: |
        cd app
        go vet ./...

  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Download dependencies
      run: make deps

    - name: Run go vet security check
      run: |
        cd app
        go vet ./...
        
    - name: Check for hardcoded secrets
      run: |
        cd app
        # Basic check for common secret patterns (excluding our test credentials)
        FOUND=$(grep -r "password\|secret\|key\|token" --include="*.go" . | grep -v "// " | grep -v "labpass123\|labroot123" | wc -l)
        if [ "$FOUND" -gt 0 ]; then
          echo "⚠️ Potential hardcoded secrets found:"
          grep -r "password\|secret\|key\|token" --include="*.go" . | grep -v "// " | grep -v "labpass123\|labroot123"
          exit 1
        else
          echo "✅ No hardcoded secrets detected"
        fi